#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*linkit$//g" /etc/opkg/distfeeds.conf

BAUDRATE=`uci get yunbridge.config.baudrate`
[ -n "${BAUDRATE}" ] || {
	uci set yunbridge.config.baudrate=2500000
	uci commit yunbridge
}

wan_mac=$(mtd_get_mac_binary factory 4)

uci set network.wan.macaddr=$wan_mac
uci commit network

uci delete uhttpd.main.alias
uci commit uhttpd

[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

. /lib/ramips.sh

uci set system.@system[-1].hostname="SDC-Clock"

uci commit
return 0
